quarkus.application.name=iss-tracker
quarkus.http.port=8080

quarkus.rest-client.iss-api.url=http://api.open-notify.org
quarkus.rest-client.iss-api.connect-timeout=3000
quarkus.rest-client.iss-api.read-timeout=5000

quarkus.log.level=INFO
quarkus.log.category."com.themainthread.iss".level=DEBUG

%dev.quarkus.scheduler.start-mode=forced
%dev.quarkus.log.category."com.themainthread.iss".level=DEBUG