# --- Database (Dev Services) ---
quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=false

# --- Configure Hashtags. If non set, all hashtags will be collected. ---
#app.hashtags=quarkus,java,jakartaee,iran,trump
app.hashtags=

# SSE endpoint
fedibuzz.streaming.url=https://fedi.buzz/api/v1/streaming/public

# Stream control
app.stream.auto-start=true

# Buffering
app.buffer.max-size=5000
app.buffer.flush-interval-seconds=5s

# Logging
quarkus.log.level=INFO
quarkus.log.category."com.example".level=INFO