quarkus.webauthn.enable-login-endpoint=true
quarkus.webauthn.enable-registration-endpoint=true

quarkus.webauthn.user-verification=required
quarkus.webauthn.resident-key=required
quarkus.webauthn.authenticator-attachment=platform
quarkus.webauthn.attestation=none

quarkus.webauthn.session-timeout=30m
quarkus.webauthn.cookie-same-site=strict

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.http.auth.session.encryption-key=whrCQOhdqYB6GDJ2ZAJy2VbFLmPCI1WK13pCOdiv2RQ=