quarkus.application.name=quarkus-grpc-service

quarkus.grpc.server.port=9000
quarkus.grpc.server.host=0.0.0.0
quarkus.grpc.server.enable-reflection-service=true

quarkus.log.level=INFO
quarkus.log.category."io.grpc".level=INFO
quarkus.container-image.build=true
