%dev.quarkus.log.console.json.enabled=false
%test.quarkus.log.console.json.enabled=false

# Global default
quarkus.log.level=INFO

# Our code more verbose
quarkus.log.category."com.noir".level=DEBUG

# Silence framework noise
quarkus.log.category."org.hibernate".level=WARN
quarkus.log.category."io.quarkus.resteasy.reactive".level=WARN

# Enable TRACE compilation
quarkus.log.min-level=TRACE

%dev.quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{3.}] [traceId=%X{traceId}] (%t) %s%e%n
%dev.quarkus.console.color=true

%prod.quarkus.log.console.json.enabled=true
%prod.quarkus.log.console.json.pretty-print=false
%prod.quarkus.log.console.json.log-format=ecs


quarkus.log.handler.file.audit.enable=true
quarkus.log.handler.file.audit.path=target/log/order-service/audit.log
quarkus.log.handler.file.audit.level=INFO
quarkus.log.handler.file.audit.format=%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ} AUDIT [%X{traceId}] %s%n

quarkus.log.category."com.noir.audit".handlers=audit
quarkus.log.category."com.noir.audit".use-parent-handlers=false

quarkus.log.console.async.enabled=true
quarkus.log.console.async.queue-length=512
quarkus.log.console.async.overflow=DISCARD