# Dev Services PostgreSQL (don’t set quarkus.datasource.jdbc.url)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.db-name=workout_db

# Use a PostGIS-capable image for Dev Services
quarkus.datasource.devservices.image-name=imresamu/postgis:17-3.6.1-bundle0-bookworm

# Run privileged init script (CREATE EXTENSION needs elevated rights)
quarkus.datasource.devservices.init-privileged-script-path=db/init-postgis.sql

# Hibernate
quarkus.hibernate-orm.schema-management.strategy = drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# Upload limits for GPX files
quarkus.http.limits.max-body-size=20M

# Server-side AWT rendering
java.awt.headless=true