quarkus.langchain4j.timeout=60s

quarkus.langchain4j.easy-rag.path-type=FILESYSTEM
quarkus.langchain4j.easy-rag.path-matcher=glob:**.txt

quarkus.langchain4j.easy-rag.max-segment-size=400
quarkus.langchain4j.easy-rag.max-overlap-size=50
quarkus.langchain4j.easy-rag.max-results=3

quarkus.langchain4j.easy-rag.path=src/main/resources/documents
quarkus.langchain4j.easy-rag.reuse-embeddings.enabled=true
quarkus.langchain4j.easy-rag.reuse-embeddings.file=banking-embeddings.json

quarkus.langchain4j.ollama.chat-model.model-id=llama3.2
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

quarkus.log.category."com.example.rag".level=DEBUG

quarkus.langchain4j.chat-memory.memory-window.max-messages=20