// Generated by jextract

package cobol;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class calcinterest_h extends calcinterest_h$shared {

    calcinterest_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("CALCINTEREST"), LIBRARY_ARENA)
            .or(SymbolLookup.libraryLookup(System.mapLibraryName("cob"), LIBRARY_ARENA))
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());


    private static class cob_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            calcinterest_h.C_INT,
            calcinterest_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cob_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void cob_init(int argc, char **argv)
     * }
     */
    public static FunctionDescriptor cob_init$descriptor() {
        return cob_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void cob_init(int argc, char **argv)
     * }
     */
    public static MethodHandle cob_init$handle() {
        return cob_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void cob_init(int argc, char **argv)
     * }
     */
    public static MemorySegment cob_init$address() {
        return cob_init.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void cob_init(int argc, char **argv)
     * }
     */
    public static void cob_init(int argc, MemorySegment argv) {
        var mh$ = cob_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cob_init", argc, argv);
            }
            mh$.invokeExact(argc, argv);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class CALCINTEREST {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            calcinterest_h.C_POINTER,
            calcinterest_h.C_POINTER,
            calcinterest_h.C_POINTER,
            calcinterest_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("CALCINTEREST");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void CALCINTEREST(char *principal, char *rate, char *years, char *result)
     * }
     */
    public static FunctionDescriptor CALCINTEREST$descriptor() {
        return CALCINTEREST.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void CALCINTEREST(char *principal, char *rate, char *years, char *result)
     * }
     */
    public static MethodHandle CALCINTEREST$handle() {
        return CALCINTEREST.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void CALCINTEREST(char *principal, char *rate, char *years, char *result)
     * }
     */
    public static MemorySegment CALCINTEREST$address() {
        return CALCINTEREST.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void CALCINTEREST(char *principal, char *rate, char *years, char *result)
     * }
     */
    public static void CALCINTEREST(MemorySegment principal, MemorySegment rate, MemorySegment years, MemorySegment result) {
        var mh$ = CALCINTEREST.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("CALCINTEREST", principal, rate, years, result);
            }
            mh$.invokeExact(principal, rate, years, result);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

