// Generated by jextract

package com.forest.flux;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class FluxLib extends FluxLib$shared {

    FluxLib() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP;

    static {
        // 1. HARDCODE your library path here.
        // This creates a direct handle to the file, bypassing ClassLoader issues.
        String libPath = "/Users/meisele/Projects/flux2.c/libflux.dylib";

        System.out.println("DEBUG: Loading library from " + libPath);

        try {
            // Load the library directly into this lookup
            SymbolLookup libLookup = SymbolLookup.libraryLookup(java.nio.file.Path.of(libPath), LIBRARY_ARENA);

            // 2. Define a lookup strategy that handles the macOS underscore automatically
            SYMBOL_LOOKUP = name -> {
                // Try exact name
                var result = libLookup.find(name);
                if (result.isPresent())
                    return result;

                // Try macOS underscore prefix
                result = libLookup.find("_" + name);
                if (result.isPresent())
                    return result;

                return java.util.Optional.empty();
            };

        } catch (Throwable t) {
            t.printStackTrace();
            throw new RuntimeException("Failed to load whisper library: " + t.getMessage(), t);
        }
    }

    private static class flux_wrapper_init {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                FluxLib.C_POINTER,
                FluxLib.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("flux_wrapper_init");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * flux_ctx *flux_wrapper_init(const char *model_path)
     * }
     */
    public static FunctionDescriptor flux_wrapper_init$descriptor() {
        return flux_wrapper_init.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * flux_ctx *flux_wrapper_init(const char *model_path)
     * }
     */
    public static MethodHandle flux_wrapper_init$handle() {
        return flux_wrapper_init.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * flux_ctx *flux_wrapper_init(const char *model_path)
     * }
     */
    public static MemorySegment flux_wrapper_init$address() {
        return flux_wrapper_init.ADDR;
    }

    /**
     * {@snippet lang = c : * flux_ctx *flux_wrapper_init(const char *model_path)
     * }
     */
    public static MemorySegment flux_wrapper_init(MemorySegment model_path) {
        var mh$ = flux_wrapper_init.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("flux_wrapper_init", model_path);
            }
            return (MemorySegment) mh$.invokeExact(model_path);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class flux_wrapper_generate {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
                FluxLib.C_INT,
                FluxLib.C_POINTER,
                FluxLib.C_POINTER,
                FluxLib.C_POINTER,
                FluxLib.C_INT,
                FluxLib.C_INT,
                FluxLib.C_INT,
                FluxLib.C_FLOAT,
                FluxLib.C_LONG);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("flux_wrapper_generate");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c
     * : * int flux_wrapper_generate(flux_ctx *ctx, const char *prompt, const char *output_path, int width, int height, int steps, float guidance, long seed)
     * }
     */
    public static FunctionDescriptor flux_wrapper_generate$descriptor() {
        return flux_wrapper_generate.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c
     * : * int flux_wrapper_generate(flux_ctx *ctx, const char *prompt, const char *output_path, int width, int height, int steps, float guidance, long seed)
     * }
     */
    public static MethodHandle flux_wrapper_generate$handle() {
        return flux_wrapper_generate.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c
     * : * int flux_wrapper_generate(flux_ctx *ctx, const char *prompt, const char *output_path, int width, int height, int steps, float guidance, long seed)
     * }
     */
    public static MemorySegment flux_wrapper_generate$address() {
        return flux_wrapper_generate.ADDR;
    }

    /**
     * {@snippet lang = c
     * : * int flux_wrapper_generate(flux_ctx *ctx, const char *prompt, const char *output_path, int width, int height, int steps, float guidance, long seed)
     * }
     */
    public static int flux_wrapper_generate(MemorySegment ctx, MemorySegment prompt, MemorySegment output_path,
            int width, int height, int steps, float guidance, long seed) {
        var mh$ = flux_wrapper_generate.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("flux_wrapper_generate", ctx, prompt, output_path, width, height, steps, guidance, seed);
            }
            return (int) mh$.invokeExact(ctx, prompt, output_path, width, height, steps, guidance, seed);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class flux_wrapper_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
                FluxLib.C_POINTER);

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("flux_wrapper_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang = c : * void flux_wrapper_free(flux_ctx *ctx)
     * }
     */
    public static FunctionDescriptor flux_wrapper_free$descriptor() {
        return flux_wrapper_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang = c : * void flux_wrapper_free(flux_ctx *ctx)
     * }
     */
    public static MethodHandle flux_wrapper_free$handle() {
        return flux_wrapper_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang = c : * void flux_wrapper_free(flux_ctx *ctx)
     * }
     */
    public static MemorySegment flux_wrapper_free$address() {
        return flux_wrapper_free.ADDR;
    }

    /**
     * {@snippet lang = c : * void flux_wrapper_free(flux_ctx *ctx)
     * }
     */
    public static void flux_wrapper_free(MemorySegment ctx) {
        var mh$ = flux_wrapper_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("flux_wrapper_free", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
            throw ex;
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}
